openapi: 3.2.0
info:
  title: Gladly Agents API
  version: '1.0'
  description: '# Introducing the Gladly API


    At Gladly, we believe that customer service is best when it''s a conversation.'
servers:
- url: https://{organization}.gladly.com/api/v1
  description: Production
  variables:
    organization:
      default: organization
      description: Your Gladly organization subdomain
- url: https://{organization}.gladly.qa/api/v1
  description: Sandbox
  variables:
    organization:
      default: organization
      description: Your Gladly QA organization subdomain
security:
- basicAuth: []
tags:
- name: Agents
  description: 'An **Agent** represents the user profile of a person who helps customers in Gladly.

    The API allows you to lookup Agents who participated in conversations with customers.'
paths:
  /api/v1/agents:
    get:
      tags:
      - Agents
      summary: List Agents
      description: Returns a list of agents.
      operationId: getAgents
      responses:
        '200':
          description: Agents
          content:
            application/json:
              schema:
                title: Agents
                type: array
                items:
                  $ref: '#/paths/~1api~1v1~1agents~1%7BagentId%7D/get/responses/200/content/application~1json/schema'
  /api/v1/agents/{agentId}:
    parameters:
    - name: agentId
      in: path
      description: id of the agent
      required: true
      schema:
        type: string
        example: WmeA3Y51Q5ayCAaZ1AotIA
    get:
      tags:
      - Agents
      summary: Get Agent
      description: Get an agent profile by their unique id.
      operationId: getAgent
      responses:
        '200':
          description: Agent
          content:
            application/json:
              schema:
                title: Agent
                type: object
                properties:
                  id:
                    type: string
                    description: Id of the agent
                    example: WmeA3Y51Q5ayCAaZ1AotIA
                  name:
                    type: string
                    description: First and last name of the agent
                    example: Amy Agent
                  emailAddress:
                    type: string
                    description: Agent's login email address
                    example: amy.agent@company.com
  /api/v1/agents/{agentId}/call-recorder:
    parameters:
    - name: agentId
      in: path
      description: Gladly ID or Gladly email address of the agent
      required: true
      schema:
        type: string
        example: WmeA3Y51Q5ayCAaZ1AotIA OR agent@customer.com
    get:
      tags:
      - Agents
      summary: Get Agent CallRecorder
      description: Get an agent call recording status.
      operationId: getAgentCallRecording
      responses:
        '200':
          description: CallRecorder
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1v1~1agents~1%7BagentId%7D~1call-recorder/patch/requestBody/content/application~1json/schema'
        '404':
          description: Agent not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                  code: not_exist
                  detail: agent WmeA3Y51Q5ayCAaZ1AotIA does not exist
    patch:
      tags:
      - Agents
      summary: Update Agent CallRecorder
      description: Update an agent's active call recording status. This API allows changing the `recording` property.
      operationId: updateAgentCallRecording
      requestBody:
        required: true
        description: JSON patch of CallRecorder
        content:
          application/json:
            schema:
              title: CallRecorder
              type: object
              properties:
                agentId:
                  type: string
                  description: Id of the agent
                  example: WmeA3Y51Q5ayCAaZ1AotIA
                customerId:
                  type: string
                  description: Id of the customer on the call, if the agent is on a call. If the agent is not on a call this is omitted
                  example: ZcyobierQhucTS5GV1R2Fw
                conversationItemId:
                  type: string
                  description: Id of the conversation item of the call, if the agent is on a call. If the agent is not on a call this is omitted
                  example: g6UatsvAQC69AcDpOKF-yQ
                recording:
                  type: boolean
                  description: If the call is currently being recorded or not
                  example: 'true'
            example:
              recording: false
      responses:
        '204':
          description: Call recording updated. If an agent is not on a call the update will do nothing.
        '404':
          description: Agent not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                  code: not_exist
                  detail: agent WmeA3Y51Q5ayCAaZ1AotIA does not exist
components:
  schemas:
    Error:
      type: object
      properties:
        attr:
          type: string
          description: Identifies the field causing the error
        code:
          type: string
          description: Code indicating the error type
        detail:
          type: string
          description: More details describing what went wrong
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example:
          - attr: content
            code: blank
            detail: content cannot be blank
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: 'Gladly API uses token-based **Basic Authentication**. API tokens are associated with designated Gladly users.

        To create and use an API token, your user must have the API User permission. An API token can be used to perform any API request without restriction.


        | user name   | password  |

        | ----------- | --------- |

        | agent email | API token |


        The credentials must be passed via an `Authorization` HTTP header. All requests must be made over HTTPS.


        ```shell

        curl -u user@organization.com:$GLADLY_API_TOKEN \

        https://organization.gladly.com/api/v1/organization

        ```

        '
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic auth — username is the API user email; password is the API token. Requires the "API User" permission.
x-tagGroups:
- name: REST API
  tags:
  - Agents
  - Public Answer
  - Answer Management
  - Audiences
  - Business Hours
  - Communications
  - Conversations
  - Customers
  - Events
  - Export
  - Freeform Topics
  - Inboxes
  - Organization
  - Proactive Conversations
  - Reports
  - Tasks
  - Teams
  - User Identity
  - Topics
  - Webhooks
- name: Webhooks
  tags:
  - Summary
  - Payloads
- name: Lookup API
  tags:
  - Customer Lookup
- name: Resources
  tags:
  - Versioning
  - Error Handling
  - Rate Limit
  - Rich Content
  - Launching Soon
